### ISSUE TITLE
Attempting to run locally on regtest

### ISSUE THREAD

**Issue by thunderbiscuit** [RCasatta/fbbe#3]
Hey Riccardo! This looks like a cool explorer. I figured I'd give it a go locally to see if I can use it when doing small local testing of different things.

Not sure why but it hangs for me with the following message: `bitcoind is still loading, waiting...`

My bitcoin daemon is definitely up and running (I can mine blocks and whatnot). Let me know if you have any idea what the problem could be!
```sh
fbbe on  master is 📦 v0.1.3 via 🦀 v1.64.0
❯ cargo run -- --network regtest
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/fbbe --network regtest`
[2023-01-18T01:27:17Z INFO  fbbe::globals] networks [Regtest]
[2023-01-18T01:27:17Z INFO  fbbe::globals] bitcoind_addr 127.0.0.1:18443
[2023-01-18T01:27:17Z WARN  fbbe] bitcoind is still loading, waiting...
[2023-01-18T01:27:27Z WARN  fbbe] bitcoind is still loading, waiting...
[2023-01-18T01:27:37Z WARN  fbbe] bitcoind is still loading, waiting...
```

**Comment by RCasatta** [comment]
Hey!
I will look into it, in the meantime I think you can use version 0.1.2 without this issue

**Comment by RCasatta** [comment]
I think the issue is that `bitcoind` is started without the `rest` flag (use `bitcoind ... --rest` or `rest=1` in bitcoin.conf)

The other issue is that the error could be discriminated or at least suggest that in the log, leaving this open until it's better handled

**Comment by thunderbiscuit** [comment]
Yes that did it!

Thanks a bunch. I just needed to run the bitcoin daemon with the `-rest` flag turned on. Loving it! I'm exploring the UI and what info it displays at the moment. Thanks for building this.

**Comment by RCasatta** [comment]
Happy you like it and thanks for trying it out!
With #4 the suggestion to use `--rest` will appear in the logs
